#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=50G
#SBATCH --job-name=datagrid_generator
#SBATCH --time=4-12:00:00
#SBATCH --output=/scratch/s4950836/%j.out

module purge
module load Python
module load Python/3.9.6-GCCcore-11.2.0

srun python3 ./data_grid_genSpectra.py