#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=50
#SBATCH --mem-per-cpu=1G
#SBATCH --job-name=datagrid_generator_py
#SBATCH --time=4-12:00:00
#SBATCH --output=/scratch/s4950836/%j.out

module purge
module load Python

srun pip install -r requirements.txt
srun python main_mp.py